import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">Spotify Analytics App!</Link>
        </h1>

        <p className={styles.description}>
            Get started by <Link href="/login" style={{textDecoration: "underline"}}>login you</Link>.
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/SimonDuperray/ESEO-NextAppSpotify"
          target="_blank"
          rel="noopener noreferrer"
        >
          © AUGER Caroline - DUPERRAY Simon
        </a>
      </footer>
    </div>
  )
};
